### ISSUE TITLE
Unhandled exception in adjacent-overload-signatures

### ISSUE THREAD

**Issue by spencerhakim** [nzakas/eslint-plugin-typescript#49]
Code:
```typescript
export class TestA{}
export class TestB{}

export type TestUnion = TestA | TestB; // this line causes error
```

Stack:
```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at getMemberName (/usr/src/app/node_modules/eslint-plugin-typescript/lib/rules/adjacent-overload-signatures.js:35:49)
    at members.forEach.member (/usr/src/app/node_modules/eslint-plugin-typescript/lib/rules/adjacent-overload-signatures.js:72:28)
    at Array.forEach (<anonymous>)
    at Linter.checkBodyForOverloadMethods (/usr/src/app/node_modules/eslint-plugin-typescript/lib/rules/adjacent-overload-signatures.js:71:25)
    at emitOne (events.js:120:20)
    at Linter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (/usr/src/app/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/usr/src/app/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/usr/src/app/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/usr/src/app/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
```

**Comment by weirdpattern** [comment]
@spencerhakim thanks for reporting this issue.. I think I know what's going on...
I will work on this

**Comment by weirdpattern** [comment]
OK, I added logic to handle exported types.
I also added some missing expressions (default exports and construct signatures in interfaces).

**Comment by xcatliu** [comment]
@weirdpattern Error occurred again:

Code:

```ts
export default function () {
    // do something
}
```

Stack:

```
Cannot read property 'name' of null
TypeError: Cannot read property 'name' of null
    at getMemberName (E:\work\playground\node_modules\eslint-plugin-typescript\lib\rules\adjacent-overload-signatures.js:46:37)
    at getMemberName (E:\work\playground\node_modules\eslint-plugin-typescript\lib\rules\adjacent-overload-signatures.js:40:27)
    at members.forEach.member (E:\work\playground\node_modules\eslint-plugin-typescript\lib\rules\adjacent-overload-signatures.js:85:28)
    at Array.forEach (native)
    at checkBodyForOverloadMethods (E:\work\playground\node_modules\eslint-plugin-typescript\lib\rules\adjacent-overload-signatures.js:84:25)
    at listeners.(anonymous function).forEach.listener (E:\work\playground\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (E:\work\playground\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (E:\work\playground\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (E:\work\playground\node_modules\eslint\lib\util\node-event-generator.js:280:22)
```

**Comment by xcatliu** [comment]
A:
```ts
export default function foo() {
    // do something
}
```

B:
```ts
export default function () {
    // do something
}
```

A was fine but B got errors

**Comment by bow3nwang** [comment]
at adjacent-overload-signatures.js line 47
```js
case "TSNamespaceFunctionDeclaration": {
    return member.id.name;
}
```
still throw exception.
Somdtimes member.id is null.

**Comment by iwata** [comment]
I had same error like below and you should reopen.

```
TypeError: Cannot read property 'name' of null
    at getMemberName (../node_modules/eslint-plugin-typescript/lib/rules/adjacent-overload-signatures.js:48:38)
    at getMemberName (../node_modules/eslint-plugin-typescript/lib/rules/adjacent-overload-signatures.js:42:27)
    at members.forEach.member (../node_modules/eslint-plugin-typescript/lib/rules/adjacent-overload-signatures.js:87:28)
    at Array.forEach (<anonymous>)
    at checkBodyForOverloadMethods (../node_modules/eslint-plugin-typescript/lib/rules/adjacent-overload-signatures.js:86:25)
    at listeners.(anonymous function).forEach.listener (../node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (../node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (../node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (../node_modules/eslint/lib/util/node-event-generator.js:280:22)
```

**Comment by macklinu** [comment]
I can't reproduce this issue in master with a unit test. I believe the fix is in place but may not have been released to npm?
